# Suggested solution of Exercise 8, Week 7

In [1]:
using HomotopyContinuation

## Part (a): Bounds

### Bézout bound

The Bézout bound is the product of the total degrees: $3 \cdot 3 = 9$.

### BKK bound in $(\mathbb{C}^*)^2$

The mixed volume is $4$.

We can compute it with the HC.jl package as follows. 

Note that the polytopes should be be given in V-representation, with the vertices as columns of a matrix.

In [2]:
P1 = [2 1 0; 1 0 1]
P2 = [1 1 0; 2 0 1]
mixed_volume([P1,P2])

4

### BKK bound in $\mathbb{C}^2$

The BKK bound in $\mathbb{C}^2$ is $5$. 

To see this, we add a vertex $(0,0)$ to each polytope before we compute the mixed volume. 

In [3]:
add_column_of_zeros = M -> hcat(M, zeros(Int,size(M,1)));

In [4]:
P1_new = add_column_of_zeros(P1)

2×4 Matrix{Int64}:
 2  1  0  0
 1  0  1  0

In [5]:
P2_new = add_column_of_zeros(P2)

2×4 Matrix{Int64}:
 1  1  0  0
 2  0  1  0

In [6]:
mixed_volume([P1_new,P2_new])

5

In [7]:
# Alternatively
mixed_volume(add_column_of_zeros.([P1,P2]))

5

## Part (b): Solution of the system

In [8]:
a = randn(6)

6-element Vector{Float64}:
 -0.5273164723989412
  0.5034480489634037
  0.7045762849205139
 -0.8371059417380496
  1.5106573497695992
  0.5148250294053449

In [9]:
@var x y
F = System([a[1]*x^2*y + a[2]*x + a[3]*y,
        a[4]*x*y^2 + a[5]*x + a[6]*y])


System of length 2
 2 variables: x, y

 0.503448048963404*x + 0.704576284920514*y - 0.527316472398941*x^2*y
 1.5106573497696*x + 0.514825029405345*y - 0.83710594173805*x*y^2

In [10]:
# Will trace as many paths as the Bézout bound
solve(F, start_system = :total_degree)

Tracking 9 paths... 100%|███████████████████████████████| Time: 0:00:04
  # paths tracked:                  9
  # non-singular solutions (real):  5 (5)
  # singular endpoints (real):      0 (0)
  # total solutions (real):         5 (5)


Result with 5 solutions
• 9 paths tracked
• 5 non-singular solutions (5 real)
• random_seed: 0x23d2e38a
• start_system: :total_degree


In [11]:
# Will trace as many paths as the mixed volume
solve(F, start_system = :polyhedral, only_non_zero = true)

Tracking 4 paths... 100%|███████████████████████████████| Time: 0:00:02
  # paths tracked:                  4
  # non-singular solutions (real):  4 (4)
  # singular endpoints (real):      0 (0)
  # total solutions (real):         4 (4)


Result with 4 solutions
• 4 paths tracked
• 4 non-singular solutions (4 real)
• random_seed: 0x2d7ca083
• start_system: :polyhedral


In [12]:
# Will trace as many paths as the BKK bound in C^n
solve(F, start_system = :polyhedral)

Tracking 5 paths... 100%|███████████████████████████████| Time: 0:00:01
  # paths tracked:                  5
  # non-singular solutions (real):  5 (5)
  # singular endpoints (real):      0 (0)
  # total solutions (real):         5 (5)


Result with 5 solutions
• 5 paths tracked
• 5 non-singular solutions (5 real)
• random_seed: 0x9919eca7
• start_system: :polyhedral


### Part (c): Discussion

| Start system | Underlying bound | Underlying theorem |Advantages | Disadvantages |
| --- | --- | --- | --- |  --- | 
| `:total_degree` | Product of the total degrees | Bézout's theorem | Fast and easy to compute | Can be a high overestimation (especially if the system is *sparse*, in the sense that we few monomials in each equation) |
| `:polyhedral` with `only_non_zero=false` (this is the default) | Mixed volume of the Newton polytopes with origin added as vertex to each polytope | Bernstein's theorem (improved version due to Li and Wang, 1996) | Often quite accurate (especially if the coefficients are "random" and "independent" enough), so fewer superflous paths |  Can be a lot harder to compute than the product of the total degrees |
| `:polyhedral` with `only_non_zero=true` | Mixed volume of the Newton polytopes | Bernstein's theorem | Even fewer superflous paths if we only want solutions in $(\mathbb{C}^*)^n$ | Still a lot harder to compute than the product of the total degrees |