# Suggested solution of Problem 8, Week 7

In [3]:
using HomotopyContinuation

## Part (a): Bounds

### Bézout bound

The Bézout bound is the product of the total degrees: $3 \cdot 3 = 9$.

### BKK bound in $(\mathbb{C}^*)^2$

The mixed volume is $4$.

We can compute it with the HC.jl package as follows. 

Note that the polytopes should be be given in V-representation, with the vertices as columns of a matrix.

In [4]:
P1 = [2 1 0; 1 0 1]
P2 = [1 1 0; 2 0 1]
mixed_volume([P1,P2])

4

### BKK bound in $\mathbb{C}^2$

The BKK bound in $\mathbb{C}^2$ is $5$. 

To see this, we add a vertex $(0,0)$ to each polytope before we compute the mixed volume. 

In [5]:
add_column_of_zeros = M -> hcat(M, zeros(Int,size(M,1)));

In [8]:
P1_new = add_column_of_zeros(P1)

2×4 Matrix{Int64}:
 2  1  0  0
 1  0  1  0

In [9]:
P2_new = add_column_of_zeros(P2)

2×4 Matrix{Int64}:
 1  1  0  0
 2  0  1  0

In [10]:
mixed_volume([P1_new,P2_new])

5

In [11]:
# Alternatively
mixed_volume(add_column_of_zeros.([P1,P2]))

5

## Part (b): Solution of the system

In [12]:
a = randn(6)

6-element Vector{Float64}:
  0.37656662188202766
  0.44655906545143736
  0.5361766234089025
  1.1972933648620736
 -0.7922331637799329
 -0.9843127757074858

In [13]:
@var x y
F = System([a[1]*x^2*y + a[2]*x + a[3]*y,
        a[4]*x*y^2 + a[5]*x + a[6]*y])


System of length 2
 2 variables: x, y

 0.446559065451437*x + 0.536176623408902*y + 0.376566621882028*x^2*y
 -0.792233163779933*x - 0.984312775707486*y + 1.19729336486207*x*y^2

In [17]:
# Will trace as many paths as the Bézout bound
solve(F, start_system = :total_degree)

Result with 5 solutions
• 9 paths tracked
• 5 non-singular solutions (3 real)
• random_seed: 0xa2ad1567
• start_system: :total_degree


In [18]:
# Will trace as many paths as the mixed volume
solve(F, start_system = :polyhedral, only_non_zero = true)

Result with 4 solutions
• 4 paths tracked
• 4 non-singular solutions (2 real)
• random_seed: 0x82d7393d
• start_system: :polyhedral


In [19]:
# Will trace as many paths as the BKK bound in C^n
solve(F, start_system = :polyhedral)

Result with 5 solutions
• 5 paths tracked
• 5 non-singular solutions (3 real)
• random_seed: 0x14fba7bb
• start_system: :polyhedral


### Part (c): Discussion

| Start system | Underlying bound | Underlying theorem |Advantages | Disadvantages |
| --- | --- | --- | --- |  --- | 
| `:total_degree` | Product of the total degrees | Bézout's theorem | Fast and easy to compute | Can be a high overestimation (especially if the system is *sparse*, in the sense that we few monomials in each equation) |
| `:polyhedral` with `only_non_zero=false` (this is the default) | Mixed volume of the Newton polytopes with origin added as vertex to each polytope | Bernstein's theorem (improved version due to Li and Wang, 1996) | Often quite accurate (especially if the coefficients are "random" and "independent" enough), so fewer superflous paths |  Can be a lot harder to compute than the product of the total degrees |
| `:polyhedral` with `only_non_zero=true` | Mixed volume of the Newton polytopes | Bernstein's theorem | Even fewer superflous paths if we only want solutions in $(\mathbb{C}^*)^n$ | Still a lot harder to compute than the product of the total degrees |