In [6]:
using HomotopyContinuation

## Mixed volume of a polytope

The HC.jl package has a built-in command for mixed volumes.

There are a few things to be aware of:

* This command wants a V-representation of the polytopes as input.
* The V-representation should be in the form of an **integer matrix** where the **columns** correspond to the vertices.

In [7]:
P = [0 1 0; 0 0 1]
Q = [0 2 0; 0 0 2]

2×3 Matrix{Int64}:
 0  2  0
 0  0  2

In [15]:
mixed_volume([P,Q])

2

## Mixed volume of a system

We can also compute the mixed volume directly from a system.

In [12]:
@var x y
F = System([1+x+y,1+x^2+y^2])

System of length 2
 2 variables: x, y

 1 + x + y
 1 + x^2 + y^2

In [13]:
mixed_volume(F)

2

## Bonus: Bound on the number of solutions in $\mathbb{C}^n$

If we want to compute the bound on the number of solutions in all of $\mathbb{C}^n$ from the Li and Wang paper, we can do the following (it's more or less what the homotopy continuation package does if we ask it to solve a system with a polyhedral start system).

In [52]:
supports, coeffs = support_coefficients(F)

(Matrix{Int32}[[1 0 0; 0 1 0], [2 0 0; 0 2 0]], Vector{Int32}[[1, 1, 1], [1, 1, 1]])

In [53]:
supports

2-element Vector{Matrix{Int32}}:
 [1 0 0; 0 1 0]
 [2 0 0; 0 2 0]

In [44]:
add_column_of_zeros = M -> [M zeros(Int,size(M,1),1)]

#27 (generic function with 1 method)

In [54]:
add_column_of_zeros(supports[1])

2×4 Matrix{Int64}:
 1  0  0  0
 0  1  0  0

In [55]:
add_column_of_zeros.(supports)

2-element Vector{Matrix{Int64}}:
 [1 0 0 0; 0 1 0 0]
 [2 0 0 0; 0 2 0 0]

In [56]:
mixed_volume(add_column_of_zeros.(supports))

2